CREATE SCHEMA `volleyball`;

CREATE TABLE `volleyball`.`spielabend` (
  `ID` INT NOT NULL,
  `TAG` DATE NULL,
  `SPIELER_ID` INT NULL,
  `WOCHEN_TAG` INT NULL,
  `SEMESTER` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));

  
CREATE TABLE `volleyball`.`spieler` (
  `ID` INT NOT NULL,
  `FIRSTNAME` VARCHAR(45) NULL,
  `NAME` VARCHAR(45) NULL,
  `GESCHLECHT` VARCHAR(45) NULL DEFAULT 'M',
  `BIRTHDATE` DATE NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `TELEFON` VARCHAR(45) NULL,
  `ACTIVE` INT 1,
   PRIMARY KEY (`ID`));
